# Generated by Django 3.2 on 2022-04-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examen_et_concours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Es',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('es_file', models.FileField(upload_to='solutions')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examen_et_concours.es'),
        ),
    ]
