# Generated by Django 3.2 on 2022-08-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_et_concours', '0002_auto_20220421_1718'),
    ]

    operations = [
       
        migrations.RenameField(
            model_name='subject',
            old_name='subject_file',
            new_name='subject_pdf',
        ),
        migrations.AddField(
            model_name='es',
            name='es_image',
            field=models.ImageField(blank=True, null=True, upload_to='solutions'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_image',
            field=models.ImageField(blank=True, null=True, upload_to='sujects'),
        ),
    ]
