# Generated by Django 3.2 on 2022-08-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20220421_1354'),
        ('examen_et_concours', '0003_auto_20220810_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='matter',
        ),
        migrations.AddField(
            model_name='es',
            name='allowed_memberships',
            field=models.ManyToManyField(to='memberships.Membership'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examen_et_concours.country'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examen_et_concours.etablissement'),
        ),
        migrations.AddField(
            model_name='level',
            name='evaluation',
            field=models.ManyToManyField(to='examen_et_concours.Evaluation'),
        ),
        migrations.AddField(
            model_name='matter',
            name='level',
            field=models.ManyToManyField(to='examen_et_concours.Level'),
        ),
        migrations.AddField(
            model_name='matter',
            name='subject',
            field=models.ManyToManyField(to='examen_et_concours.Subject'),
        ),
    ]
