# Generated by Django 3.2 on 2022-08-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen_et_concours', '0004_auto_20220811_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='matter',
            field=models.ManyToManyField(to='examen_et_concours.Matter'),
        ),
    ]
