# Generated by Django 4.1 on 2022-08-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("examen_et_concours", "0007_subject_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="level",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="examen_et_concours.level"
            ),
        ),
    ]
