# Generated by Django 3.1.1 on 2020-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujets',
            name='course_image',
            field=models.ImageField(default='media/default.jpg', upload_to='kurs_images'),
        ),
    ]
