# Generated by Django 3.1.1 on 2020-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librairie', '0002_auto_20201108_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='librairie_image'),
        ),
    ]
